<?php

/**
 * @file
 * Main module implementation of (clickable) popular tags.
 */

use \Drupal\Core\Form\FormStateInterface;
use \Drupal\popular_tags\Plugin\Field\FieldWidget\EntityReferenceAutocompleteTagsWidget;

/**
 * Implements hook_field_widget_info_alter().
 */
function popular_tags_field_widget_info_alter(array &$info) {
  if (isset($info['entity_reference_autocomplete_tags'])) {
    $info['entity_reference_autocomplete_tags']['class'] = EntityReferenceAutocompleteTagsWidget::class;
  }
}

/**
 * Implements hook_field_widget_form_alter().
 *
 * Alters any form where a taxonomy_autocomplete widget is used with
 * popular_tags setting ON.
 *
 * Or we can implement hook_field_widget_WIDGET_TYPE_form_alter
 * (popular_tags_field_widget_entity_reference_autocomplete_tags_form_alter)
 *
 * @param array $element
 *   form element to alter
 * @param array $form_state
 *   not used
 * @param array $context
 *   form element context
 */
function popular_tags_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  // $context has keys ... form, widget, items, delta, default
  $widget = $context['widget'];
  $plugin_id = $widget->getPluginId();
  // Alternative: $widget instanceof EntityReferenceAutocompleteTagsWidget
  if($plugin_id == 'entity_reference_autocomplete_tags') {
    // ksm($element); // $element['target_id'] is the actual element
    // ksm($widget);
    // ksm($plugin_id);
    $settings = $widget->getSettings();
    // ksm($settings);
    if(!empty($settings['popular_tags']['use'])) {
      // module_load_include('inc', 'popular_tags', 'popular_tags.widget');
      // _popular_tags_inject($element, $context);
    }
  }
}
