<?php

/**
 * Implements hook_form_field_ui_field_edit_form_alter(). Which allows us to
 * inject a checkbox in the field instance's settings form. This chekcbox, when
 * checked, will add clickable popular tags to any tag autocomplete widget.
 * 
 * @param type $form
 * @param type $form_state
 * @param type $form_id 
 */
function popular_tags_form_field_ui_field_edit_form_alter(&$form, &$form_state, $form_id) {
  $instance = $form['#instance']; // field instance
  if ($instance['widget']['type'] == 'taxonomy_autocomplete') {
    // if this is a taxonomy_autocomplete widget then add the popular_tags
    // checkbox to the field edit form. We don't have to do anything to save
    // this setting since the form element path is insta/widget/settings/...
    $form['instance']['widget']['settings']['popular_tags'] = array(
        '#type' => 'checkbox',
        '#title' => t('Use Clickable Popular Tags'),
        '#description' => t('Present the users with most popular terms and allow them to select tags by clicking on them.'),
        '#default_value' => @$instance['widget']['settings']['popular_tags'],
    );
  }
}

/**
 * Implements hook_field_widget_form_alter(). Alters any form where a
 * taxonomy_autocomplete widget is used with popular_tags setting ON.
 * 
 * @param type $element
 * @param type $form_state
 * @param type $context 
 */
function popular_tags_field_widget_form_alter(&$element, &$form_state, $context) {
  if ($context['instance']['widget']['type'] == 'taxonomy_autocomplete' && !empty($context['instance']['widget']['settings']['popular_tags'])) {
    module_load_include('inc', 'popular_tags', 'popular_tags.widget');
    _popular_tags_inject($element, $context);
  }
}
